### PR TITLE
don't add matching quote for single quote strings

### PR DESCRIPTION
**Pull request by trendzetter**
don't add a "matching" quote for single quote strings

### CODE REVIEW

**Comment by trendzetter** [comment]
that list of autocompleteCharacters could probably be tinned out or added to but I am not a pact specialist.

**Comment by sirlensalot** [comment]
I don't understand, this change _suppresses_ closing delimiters? Also please give PR a semantic name e.g. "don't add matching quote for single quote strings"

**Comment by trendzetter** [comment]
Without the change when typing a single quote atom would automatically add a second. This doesn't make sense in pact as far as I can tell. I made this change on request of Thanos. Please let me know if you like more clarification.

**Comment by ggobugi27** [comment]
Looks good, Can you add `'<>'` to the bracket matcher?

**Comment by trendzetter** [comment]
added. Nothing to purge from the list? These are the defaults from atom extension bracket-matcher without the single quote matcher.

**Review by ggobugi27 — APPROVED** [review]

**Pull request merged**
